_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: fr
uuid: 1e4e4307-0adf-42fe-9312-fd860b9b94a3
name: 'INC - Dashboard'
mail: admin@inc.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: fr
mail_notification: ''
